@host = http://localhost:3000/api

###
# @name menus
GET {{host}}/menu/get Http/1.1
Content-Type: application/json

###
# @name menus
POST  {{host}}/car-wash/post Http/1.1
Content-Type: application/json

{
  "name": "Test Car Wash",
  "path": "test-car-wash",
  "branch": "test-branch",
  "landmark": "Test Landmark",
  "lat": 1.234567,
  "long": 45.678901,
  "logo": "path/to/test/logo.png",
  "areaId": "clq4v2spn000p6yr6qrgdlmwy",
  "bookingLeadTime": 1,
  "carWashServices": [
    {
      "serviceId": "clq4v2sme00036yr6ieh07csu",
      "cost": 300,
      "carTypes": [
        {
          "id": "clq4v2sob00086yr6wdfud3l6"
        },
        {
          "id": "clq4v2sos00096yr6stx3feyx"
        }
      ]
    },
    {
      "serviceId": "clq4v2smw00046yr69uibkzd3",
      "cost": 200,
      "carTypes": [
        {
          "id": "clq4v2sos00096yr6stx3feyx"
        },
        {
          "id": "clq4v2sp6000a6yr6duilekgh"
        }
      ]
    }
  ]
}